import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguageCode = 'fr'; // 'fr', 'en', 'mos', 'diu'

  String get currentLanguageCode => _currentLanguageCode;

  void setLanguage(String code) {
    if (['fr', 'en', 'mos', 'diu'].contains(code)) {
      _currentLanguageCode = code;
      notifyListeners();
    }
  }

  // Base translations logic
  String translate(String key) {
    return _translations[_currentLanguageCode]?[key] ?? _translations['fr']?[key] ?? key;
  }

  final Map<String, Map<String, String>> _translations = {
    'fr': {
      'settings': 'Paramètres',
      'general': 'GÉNÉRAL',
      'app_language': 'Langue de l\'application',
      'theme_dark': 'Mode Sombre',
      'security_privacy': 'SÉCURITÉ ET CONFIDENTIALITÉ',
      'auth_biometric': 'Authentification biométrique',
      'auth_biometric_sub': 'Utiliser Face ID / Touch ID pour se connecter',
      'change_password': 'Changer le mot de passe',
      'app_security_admin': 'Sécurité de l\'application et de l\'administrateur',
      'notifications_title': 'NOTIFICATIONS',
      'push_notifications': 'Notifications Push',
      'push_notifications_sub': 'Recevoir des alertes pour vos réservations',
      'about': 'À PROPOS',
      'terms_of_use': 'Conditions d\'utilisation',
      'privacy_policy': 'Politique de confidentialité',
      'my_profile': 'Mon Profil',
      'my_addresses': 'Mes adresses',
      'help_support': 'Aide & Support',
      'security_app': 'Sécurité (App)',
      'language': 'Langue',
      'display_mode': 'Mode d\'affichage',
      'logout': 'Se déconnecter',
      'home': 'Accueil',
      'destinations': 'Destinations',
      'reservations': 'Réservations',
      'hello': 'Bonjour 👋',
      'where_to_go': 'Où voulez-vous aller ?',
      'popular': 'Populaires',
      'categories': 'Catégories',
      'explore': 'Explorez',
      'search': 'Rechercher...',
      'all': 'Tous',
      'culture': 'Culture',
      'adventure': 'Aventure',
      'nature': 'Nature',
      'all_destinations': 'Toutes les destinations',
      'search_destination': 'Rechercher une destination...',
      'no_destination': 'Aucune destination trouvée',
      'details': 'Détails',
      'added_favorites': 'Ajouté aux favoris',
      'destination_not_found': 'Destination non trouvée',
      'description': 'Description',
      'category': 'Catégorie',
      'traveler_reviews': 'Avis des voyageurs',
      'book_now': 'Réserver maintenant',
      'book_destination': 'Réserver une destination',
      'selected_destination': 'Destination sélectionnée',
      'reservation_details': 'Détails de la réservation',
      'start_date': 'Date de début',
      'end_date': 'Date de fin',
      'number_of_people': 'Nombre de personnes',
      'comment_optional': 'Commentaire (optionnel)',
      'add_special_requests': 'Ajoutez vos demandes spéciales...',
      'continue_to_payment': 'Continuer vers le paiement',
      'reservation_summary': 'Récapitulatif de réservation',
      'dates': 'Dates',
      'price_per_person_day': 'Prix par personne/jour',
      'total': 'Total',
      'destination_singular': 'Destination',
      'days_short': 'j',
      'payment': 'Paiement',
      'payment_summary': 'Résumé du paiement',
      'amount_to_pay': 'Montant à payer',
      'card_information': 'Informations de la carte',
      'card_number': 'Numéro de carte',
      'card_holder_name': 'Nom du titulaire',
      'first_last_name': 'Nom Prénom',
      'expiration': 'Expiration',
      'cvv': 'CVV',
      'accept_payment_terms': 'J\'accepte les conditions de paiement',
      'confirm_payment': 'Confirmer le paiement',
      'fill_all_fields': 'Veuillez remplir tous les champs',
      'payment_successful': 'Paiement réussi',
      'reservation_confirmed': 'Votre réservation a été confirmée avec succès!',
      'ok': 'OK',
      'error': 'Erreur:',
      'welcome_login': 'Bienvenue ! Connectez-vous',
      'email': 'Email',
      'enter_email': 'Veuillez entrer votre email',
      'enter_valid_email': 'Veuillez entrer un email valide',
      'password': 'Mot de passe',
      'enter_password': 'Veuillez entrer votre mot de passe',
      'password_length_error': 'Le mot de passe doit contenir au moins 6 caractères',
      'feature_coming_soon': 'Fonctionnalité à venir',
      'forgot_password': 'Mot de passe oublié ?',
      'login': 'Se connecter',
      'or': 'OU',
      'no_account': 'Vous n\'avez pas de compte ?',
      'register': 'S\'inscrire',
      'create_account': 'Créer un compte',
      'join_us': 'Rejoignez-nous pour explorer les merveilles du Burkina Faso',
      'full_name': 'Nom complet',
      'enter_name': 'Veuillez entrer votre nom',
      'confirm_password': 'Confirmer le mot de passe',
      'enter_confirm_password': 'Veuillez confirmer votre mot de passe',
      'passwords_do_not_match': 'Les mots de passe ne correspondent pas',
      'already_have_account': 'Vous avez déjà un compte ?',
      'my_reservations': 'Mes réservations',
      'pending_status': 'En attente',
      'confirmed_status': 'Confirmées',
      'cancelled_status': 'Annulées',
      'no_reservations': 'Aucune réservation',
      'persons': 'personne(s)',
      'days': 'jour(s)',
      'review': 'Avis',
      'cancel': 'Annuler',
      'confirmed': 'Confirmée',
      'cancelled': 'Annulée',
      'leave_review': 'Laisser un avis',
      'rating': 'Note',
      'comment': 'Commentaire',
      'share_experience': 'Partagez votre expérience...',
      'send': 'Envoyer',
      'review_added_success': 'Avis ajouté avec succès!',
      'confirm_cancellation': 'Confirmer l\'annulation',
      'cancel_reservation_confirmation': 'Êtes-vous sûr de vouloir annuler cette réservation?',
      'yes': 'Oui',
      'no': 'Non',
      'reservation_cancelled': 'Réservation annulée',
      'edit_profile': 'Modifier le Profil',
      'save_changes': 'Sauvegarder les modifications',
      'profile_updated': 'Profil mis à jour !',
      'add_new_address': 'Ajouter une nouvelle adresse',
      'add_address': 'Ajouter une adresse',
      'edit_address': 'Modifier l\'adresse',
      'address_name_hint': 'Nom (ex: Domicile, Bureau)',
      'full_address': 'Adresse complète',
      'delete': 'Supprimer',
      'address_deleted': 'Adresse supprimée',
      'save': 'Sauvegarder',
      'address_saved_success': 'Adresse enregistrée avec succès !',
      'need_help': 'Besoin d\'aide ?',
      'support_message': 'Notre équipe de support est disponible 24/7 pour vous assister avec TourBF. N\'hésitez pas à nous contacter pour toute question.',
      'write_to_us': 'Nous Écrire',
      'close': 'Fermer',
      'opening_messaging': 'Ouverture de la messagerie...',
    },
    'en': {
      'settings': 'Settings',
      'general': 'GENERAL',
      'app_language': 'Application Language',
      'theme_dark': 'Dark Mode',
      'security_privacy': 'SECURITY AND PRIVACY',
      'auth_biometric': 'Biometric Authentication',
      'auth_biometric_sub': 'Use Face ID / Touch ID to sign in',
      'change_password': 'Change Password',
      'app_security_admin': 'App and Admin Security',
      'notifications_title': 'NOTIFICATIONS',
      'push_notifications': 'Push Notifications',
      'push_notifications_sub': 'Receive alerts for your reservations',
      'about': 'ABOUT',
      'terms_of_use': 'Terms of Use',
      'privacy_policy': 'Privacy Policy',
      'my_profile': 'My Profile',
      'my_addresses': 'My Addresses',
      'help_support': 'Help & Support',
      'security_app': 'Security (App)',
      'language': 'Language',
      'display_mode': 'Display Mode',
      'logout': 'Log Out',
      'home': 'Home',
      'destinations': 'Destinations',
      'reservations': 'Reservations',
      'hello': 'Hello 👋',
      'where_to_go': 'Where do you want to go?',
      'popular': 'Popular',
      'categories': 'Categories',
      'explore': 'Explore',
      'search': 'Search...',
      'all': 'All',
      'culture': 'Culture',
      'adventure': 'Adventure',
      'nature': 'Nature',
      'all_destinations': 'All destinations',
      'search_destination': 'Search a destination...',
      'no_destination': 'No destination found',
      'details': 'Details',
      'added_favorites': 'Added to favorites',
      'destination_not_found': 'Destination not found',
      'description': 'Description',
      'category': 'Category',
      'traveler_reviews': 'Traveler Reviews',
      'book_now': 'Book Now',
      'book_destination': 'Book a destination',
      'selected_destination': 'Selected Destination',
      'reservation_details': 'Reservation Details',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'number_of_people': 'Number of People',
      'comment_optional': 'Comment (Optional)',
      'add_special_requests': 'Add your special requests...',
      'continue_to_payment': 'Continue to Payment',
      'reservation_summary': 'Reservation Summary',
      'dates': 'Dates',
      'price_per_person_day': 'Price per person/day',
      'total': 'Total',
      'destination_singular': 'Destination',
      'days_short': 'd',
      'payment': 'Payment',
      'payment_summary': 'Payment Summary',
      'amount_to_pay': 'Amount to pay',
      'card_information': 'Card Information',
      'card_number': 'Card Number',
      'card_holder_name': 'Cardholder Name',
      'first_last_name': 'First Last Name',
      'expiration': 'Expiration',
      'cvv': 'CVV',
      'accept_payment_terms': 'I accept the payment terms',
      'confirm_payment': 'Confirm Payment',
      'fill_all_fields': 'Please fill all fields',
      'payment_successful': 'Payment Successful',
      'reservation_confirmed': 'Your reservation was successfully confirmed!',
      'ok': 'OK',
      'error': 'Error:',
      'welcome_login': 'Welcome! Please log in',
      'email': 'Email',
      'enter_email': 'Please enter your email',
      'enter_valid_email': 'Please enter a valid email',
      'password': 'Password',
      'enter_password': 'Please enter your password',
      'password_length_error': 'Password must be at least 6 characters',
      'feature_coming_soon': 'Feature coming soon',
      'forgot_password': 'Forgot password?',
      'login': 'Log In',
      'or': 'OR',
      'no_account': 'Don\'t have an account?',
      'register': 'Register',
      'create_account': 'Create an account',
      'join_us': 'Join us to explore the wonders of Burkina Faso',
      'full_name': 'Full name',
      'enter_name': 'Please enter your name',
      'confirm_password': 'Confirm password',
      'enter_confirm_password': 'Please confirm your password',
      'passwords_do_not_match': 'Passwords do not match',
      'already_have_account': 'Already have an account?',
      'my_reservations': 'My reservations',
      'pending_status': 'Pending',
      'confirmed_status': 'Confirmed',
      'cancelled_status': 'Cancelled',
      'no_reservations': 'No reservations',
      'persons': 'person(s)',
      'days': 'day(s)',
      'review': 'Review',
      'cancel': 'Cancel',
      'confirmed': 'Confirmed',
      'cancelled': 'Cancelled',
      'leave_review': 'Leave a review',
      'rating': 'Rating',
      'comment': 'Comment',
      'share_experience': 'Share your experience...',
      'send': 'Send',
      'review_added_success': 'Review added successfully!',
      'confirm_cancellation': 'Confirm cancellation',
      'cancel_reservation_confirmation': 'Are you sure you want to cancel this reservation?',
      'yes': 'Yes',
      'no': 'No',
      'reservation_cancelled': 'Reservation cancelled',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save changes',
      'profile_updated': 'Profile updated!',
      'add_new_address': 'Add a new address',
      'add_address': 'Add an address',
      'edit_address': 'Edit address',
      'address_name_hint': 'Name (e.g., Home, Office)',
      'full_address': 'Full address',
      'delete': 'Delete',
      'address_deleted': 'Address deleted',
      'save': 'Save',
      'address_saved_success': 'Address saved successfully!',
      'need_help': 'Need help?',
      'support_message': 'Our support team is available 24/7 to assist you with TourBF. Do not hesitate to contact us with any questions.',
      'write_to_us': 'Write to Us',
      'close': 'Close',
      'opening_messaging': 'Opening messaging...',
    },
    'mos': {
      'settings': 'Baosgo',
      'general': 'B VUIRE',
      'app_language': 'Gom-biis',
      'theme_dark': 'Lik Soaba',
      'security_privacy': 'ZAN-YIDIGO LA GŨBG',
      'auth_biometric': 'Neng-vui b sõngre',
      'auth_biometric_sub': 'Tũnug Face ID / Touch ID n tũnge',
      'change_password': 'Toeem Sũg-zoeta',
      'app_security_admin': 'Gũbg la Kãsem-dãmb tũnge',
      'notifications_title': 'KOEESE',
      'push_notifications': 'Koeese sã n wa',
      'push_notifications_sub': 'Kẽed-y ne y sigri koeese',
      'about': 'WElGRE',
      'terms_of_use': 'Tũudum noore',
      'privacy_policy': 'Gũbg noore',
      'my_profile': 'M Vui-n-yẽ',
      'my_addresses': 'M Zĩiga',
      'help_support': 'Sõngre',
      'security_app': 'Gũbg (App)',
      'language': 'Gom-biis',
      'display_mode': 'Vui lik/peelgo',
      'logout': 'Yi',
      'home': 'Yiri',
      'destinations': 'Belem-dãmb',
      'reservations': 'Sigri',
      'hello': 'Ne y yibeoogo 👋',
      'where_to_go': 'Y sẽn dat n kẽng zĩig bʋgo?',
      'popular': 'Sẽn wʋm',
      'categories': 'Bʋʋsa',
      'explore': 'Ges-y',
      'search': 'Bao...',
      'all': 'Faasa',
      'culture': 'Rog-n-miki',
      'adventure': 'Gãnega',
      'nature': 'Weoogo',
      'all_destinations': 'Belem-dãmb faasa',
      'search_destination': 'Bao belem-dãmb...',
      'no_destination': 'Belem-dãmb la sẽn pa yã',
      'details': 'Vẽnegr võore',
      'added_favorites': 'B paasă nonge',
      'destination_not_found': 'B pa yã belem yɛ',
      'description': 'Vẽnegre',
      'category': 'Bʋʋs-yɩɩb',
      'traveler_reviews': 'Ges-tõndba koeese',
      'book_now': 'Sigr masã',
      'book_destination': 'Sigr belem',
      'selected_destination': 'Belem sẽn yãk',
      'reservation_details': 'Sigr vẽnegre',
      'start_date': 'Singr raar',
      'end_date': 'Baasg raar',
      'number_of_people': 'Ninsaalb sõor',
      'comment_optional': 'Koeese (Yãk yam)',
      'add_special_requests': 'Paas y ratem tɩ ratem...',
      'continue_to_payment': 'Kẽng yãmb yaoogo',
      'reservation_summary': 'Sigr sẽn wa n tallã',
      'dates': 'Dato',
      'price_per_person_day': 'Ninsaalb ligd / raar',
      'total': 'Faa',
      'destination_singular': 'Belem',
      'days_short': 'd',
      'payment': 'Yaoogo',
      'payment_summary': 'Yaoogo kɔrɔbɔ',
      'amount_to_pay': 'Ligd sẽn segd n yao',
      'card_information': 'Kart koɛɛse',
      'card_number': 'Kart nimero',
      'card_holder_name': 'Kart soab yʋʋre',
      'first_last_name': 'Yʋʋre',
      'expiration': 'Baasgo',
      'cvv': 'CVV',
      'accept_payment_terms': 'M sakda yaoogo noore',
      'confirm_payment': 'Sak yaoogo',
      'fill_all_fields': 'A pidg zĩig faasa',
      'payment_successful': 'Yaoogo talla neere',
      'reservation_confirmed': 'Y sigri talla neere!',
      'ok': 'N-YE',
      'error': 'Wẽnga:',
      'welcome_login': 'Ne y waongo! Kẽed-y',
      'email': 'Imeel',
      'enter_email': 'Kẽes-y y imeel',
      'enter_valid_email': 'Kẽes-y imeel sẽn yaa sɩda',
      'password': 'Sũg-zoeta',
      'enter_password': 'Kẽes-y y sũg-zoeta',
      'password_length_error': 'Sũg-zoeta segd n tara gʋls-biis a 6',
      'feature_coming_soon': 'Na n wa n yi',
      'forgot_password': 'Y yĩm-a y sũg-zoeta bɩ?',
      'login': 'Kẽnge',
      'or': 'WALLA',
      'no_account': 'Y pa tar kẽedg bɩ?',
      'register': 'Gʋls-y y yʋʋre',
      'create_account': 'Naan kẽedg zĩiga',
      'join_us': 'Naag-y-d n bãng Burkina Faso zĩ-neerse',
      'full_name': 'Yʋ-peelem',
      'enter_name': 'Kẽes-y y yʋʋre',
      'confirm_password': 'Sake sũg-zoeta',
      'enter_confirm_password': 'Kẽes-y y sũg-zoeta sɩd-sɩda',
      'passwords_do_not_match': 'Sũg-zoeta pa wõneg taab ye',
      'already_have_account': 'Y tar kẽedg zĩig bɩ?',
      'my_reservations': 'M sigri',
      'pending_status': 'Sẽn gũud neere',
      'confirmed_status': 'Sẽn sak neere',
      'cancelled_status': 'Sẽn gɩdg neere',
      'no_reservations': 'Sigri baa a yembre ka be ye',
      'persons': 'ninsaala',
      'days': 'daare',
      'review': 'Hakilina',
      'cancel': 'Gɩdge',
      'confirmed': 'Sake',
      'cancelled': 'Gɩdg-y',
      'leave_review': 'Kẽes-y y hakilina',
      'rating': 'Saangre',
      'comment': 'Kuma',
      'share_experience': 'Kɩt-y tɩ d bãng y tẽebo...',
      'send': 'Tõnge',
      'review_added_success': 'Y hakilina kẽe neere!',
      'confirm_cancellation': 'Sak gɩdgre',
      'cancel_reservation_confirmation': 'Y sɩd rat n gɩdg a sigri kãnga bɩ?',
      'yes': 'N-YE',
      'no': 'AYO',
      'reservation_cancelled': 'Sigri gɩdge',
      'edit_profile': 'Maan y profile manegre',
      'save_changes': 'Zĩig manegre',
      'profile_updated': 'Profile manegre!',
      'add_new_address': 'Paas zĩ-goosneema',
      'add_address': 'Paas zĩ-goosneema',
      'edit_address': 'Maneg zĩ-goosneema',
      'address_name_hint': 'Yʋʋre (zĩ-yiri, tʋʋmde)',
      'full_address': 'Zĩ-goosneema peelem',
      'delete': 'Yees',
      'address_deleted': 'Zĩ-goosneema yiisge',
      'save': 'Sake',
      'address_saved_success': 'Zĩ-goosneema kẽe neere!',
      'need_help': 'Y rat sõngr bɩ?',
      'support_message': 'D tʋʋmd dãmba bee ne yãmb wakat fãa n sõng TourBF wɛɛngẽ. Ra rẽgse n kos sõngre.',
      'write_to_us': 'Gʋls dãmba',
      'close': 'Pãge',
      'opening_messaging': 'B paka gʋlsg zĩiga...',
    },
    'diu': {
      'settings': 'Ladjɛlilan',
      'general': 'KƆNƆKƆW',
      'app_language': 'Kan',
      'theme_dark': 'Dibiman Cogo',
      'security_privacy': 'KANA BƆ Ɔ KƆNƆ',
      'auth_biometric': 'Ɲɛ-lajɛlan jɛgɛ',
      'auth_biometric_sub': 'Baara ni Face ID / Touch ID',
      'change_password': 'Yɛlɛma Gundo-kumaden',
      'app_security_admin': 'App latigɛ kɔnɔba la',
      'notifications_title': 'KUMABƆ',
      'push_notifications': 'Kumabɔw Jigi',
      'push_notifications_sub': 'Sɔrɔ i ta donɲɛnagofɛnfɛnw',
      'about': 'MABƐN',
      'terms_of_use': 'Baaracogo Sariya',
      'privacy_policy': 'Kasi Komin Sariya',
      'my_profile': 'N ta Kɔw',
      'my_addresses': 'N ta So',
      'help_support': 'Dɛmɛn & Fɛ',
      'security_app': 'Lakana (App)',
      'language': 'Kan',
      'display_mode': 'Yelencogo',
      'logout': 'Bɔ kɛnɛma',
      'home': 'So',
      'destinations': 'Ta-yɔrɔw',
      'reservations': 'Mara-yɔrɔw',
      'hello': 'I ni sɔgɔma 👋',
      'where_to_go': 'I bɛ fɛ ka taa min?',
      'popular': 'Mɔgɔw bɛ min fɛ',
      'categories': 'Suguya',
      'explore': 'Lajɛ',
      'search': 'Ɲini...',
      'all': 'Bɛɛ',
      'culture': 'Lada',
      'adventure': 'Taama',
      'nature': 'Kungokɔnɔ',
      'all_destinations': 'Ta-yɔrɔw bɛɛ',
      'search_destination': 'Ɲini taamana...',
      'no_destination': 'Ta-yɔrɔw ma sɔrɔ',
      'details': 'Cogo-ɲuman',
      'added_favorites': 'A fara ɲɛtaji kan',
      'destination_not_found': 'Ta-yɔrɔ ma sɔrɔ',
      'description': 'Mabɛn',
      'category': 'Suguya',
      'traveler_reviews': 'Taamadenw Hakilina',
      'book_now': 'Mara sisan',
      'book_destination': 'Mara ta-yɔrɔ',
      'selected_destination': 'Ta-yɔrɔ sugandilen',
      'reservation_details': 'Mara cogo',
      'start_date': 'Damina don',
      'end_date': 'Laban don',
      'number_of_people': 'Mɔgɔ hakɛ',
      'comment_optional': 'Kuma (A tɛ wajibiya)',
      'add_special_requests': 'A fara i ta ɲininiw kan...',
      'continue_to_payment': 'Taa sara yɔrɔ',
      'reservation_summary': 'Mara kɔrɔbɔ',
      'dates': 'Donw',
      'price_per_person_day': 'Mɔgɔ kelen kelen sara/don',
      'total': 'A Bɛɛ',
      'destination_singular': 'Ta-yɔrɔ',
      'days_short': 'd',
      'payment': 'Sara',
      'payment_summary': 'Sara kɔrɔbɔ',
      'amount_to_pay': 'Wari min ka kan ka sara',
      'card_information': 'Karti kibaruw',
      'card_number': 'Karti nimɔrɔ',
      'card_holder_name': 'Karti tigi tɔgɔ',
      'first_last_name': 'Tɔgɔ',
      'expiration': 'Laban',
      'cvv': 'CVV',
      'accept_payment_terms': 'N sɔnna sara sariyaw ma',
      'confirm_payment': 'Sara sɔn',
      'fill_all_fields': 'Yɔrɔ bɛɛ dafa',
      'payment_successful': 'Sara ɲɛna',
      'reservation_confirmed': 'I ta mara ɲɛna kosɛbɛ!',
      'ok': 'ƆWƆ',
      'error': 'Fili:',
      'welcome_login': 'I ni tiɛntigiya! Don',
      'email': 'Imeeli',
      'enter_email': 'I ta imeeli sɛbɛn',
      'enter_valid_email': 'Imeeli ɲuman sɛbɛn',
      'password': 'Gundo-kumaden',
      'enter_password': 'I ta gundo-kumaden sɛbɛn',
      'password_length_error': 'Gundo-kumaden ka kan ka sɔrɔ 6',
      'feature_coming_soon': 'Kɔw nata',
      'forgot_password': 'Gundo-kumaden ɲinan na wa?',
      'login': 'Don',
      'or': 'WALI',
      'no_account': 'Kontu tɛ i bolo wa?',
      'register': 'Tɔgɔ Sɛbɛn',
      'create_account': 'Kontu d\'a dan',
      'join_us': 'Fara an kan ka Burkina Faso kabakow lajɛ',
      'full_name': 'Tɔgɔ dafa',
      'enter_name': 'I ta tɔgɔ sɛbɛn',
      'confirm_password': 'Gundo-kumaden sɔn',
      'enter_confirm_password': 'I ta gundo-kumaden sɔn',
      'passwords_do_not_match': 'Gundo-kumadenw tɛ kelen ye',
      'already_have_account': 'Kontu bɛ i bolo wa?',
      'my_reservations': 'Ne ta mara min',
      'pending_status': 'Makounyan',
      'confirmed_status': 'Sɔn-ne',
      'cancelled_status': 'Ba-la-se-n',
      'no_reservations': 'Mara si te yen',
      'persons': 'mɔgɔ',
      'days': 'don',
      'review': 'Mikili',
      'cancel': 'Dabila',
      'confirmed': 'Sɔn-na',
      'cancelled': 'Dabila-la',
      'leave_review': 'I ta mikili di',
      'rating': 'Jari',
      'comment': 'Kuma',
      'share_experience': 'I bolo ko ɲɛfo...',
      'send': 'Ci',
      'review_added_success': 'Mikili fara a kan ɲɛna!',
      'confirm_cancellation': 'Dabila sɔn',
      'cancel_reservation_confirmation': 'I la don ka ladi ko i bi n in mara dabila?',
      'yes': 'ƆWƆ',
      'no': 'AYI',
      'reservation_cancelled': 'Mara dabila-la',
      'edit_profile': 'I ta ɲɛ kura',
      'save_changes': 'Yɛlɛma mara',
      'profile_updated': 'ɲɛ kura!',
      'add_new_address': 'Sigida kura fara a kan',
      'add_address': 'Sigida fara a kan',
      'edit_address': 'Sigida yɛlɛma',
      'address_name_hint': 'Tɔgɔ (misali, so, baara)',
      'full_address': 'Sigida dafa',
      'delete': 'A bɔ',
      'address_deleted': 'Sigida bɔla',
      'save': 'A mara',
      'address_saved_success': 'Sigida mara la ɲɛna!',
      'need_help': 'Mako bɛ dɛmɛn na?',
      'support_message': 'An ta dɛmɛn tɔn bɛ sɔrɔ waati bɛɛ TourBF la. Kana sigi sigi k’an weele kɔninya kama.',
      'write_to_us': 'Sɛbɛn an ma',
      'close': 'A datugu',
      'opening_messaging': 'Sɛbɛnni da yɛlɛla...',
    },
  };
}
